steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/backend", "." ]
  # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/$PROJECT_ID/backend" ]
  # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run", "deploy", "backend",
      "--image=gcr.io/$PROJECT_ID/backend",
      "--service-account=agora-backend-deployer@agoradesecrivains.iam.gserviceaccount.com",
      "--concurrency=100",
      "--timeout=60",
      "--min-instances=1",
      "--max-instances=10",
      "--memory=512Mi",
      "--cpu=1",
      "--vpc-connector=projects/agoradesecrivains/locations/europe-west9/connectors/backend-api",
      "--set-secrets=POSTGRES_URL=agora-postgres-dsn:latest,SENDGRID_API_KEY=sendgrid-api-key:latest",
      "--region=europe-west9",
      "--platform=managed",
      "--allow-unauthenticated",
      "--project=$PROJECT_ID"
    ]

logsBucket: "gs://logs-cloudbuild-backend"
options:
  logging: GCS_ONLY
