// Code generated by mockery v2.20.0. DO NOT EDIT.

package improve_request_service

import (
	context "context"
	"github.com/a-novel/agora-backend/domains/forum/storage/improve_request"
	"github.com/a-novel/agora-backend/models"

	mock "github.com/stretchr/testify/mock"
	time "time"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, title, content, id, now
func (_m *MockService) Create(ctx context.Context, userID uuid.UUID, title string, content string, id uuid.UUID, now time.Time) (*models.ImproveRequest, error) {
	ret := _m.Called(ctx, userID, title, content, id, now)

	var r0 *models.ImproveRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, uuid.UUID, time.Time) (*models.ImproveRequest, error)); ok {
		return rf(ctx, userID, title, content, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, uuid.UUID, time.Time) *models.ImproveRequest); ok {
		r0 = rf(ctx, userID, title, content, id, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImproveRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, title, content, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - title string
//   - content string
//   - id uuid.UUID
//   - now time.Time
func (_e *MockService_Expecter) Create(ctx interface{}, userID interface{}, title interface{}, content interface{}, id interface{}, now interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, userID, title, content, id, now)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, title string, content string, id uuid.UUID, now time.Time)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(uuid.UUID), args[5].(time.Time))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *models.ImproveRequest, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, uuid.UUID, time.Time) (*models.ImproveRequest, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRevision provides a mock function with given fields: ctx, userID, sourceID, title, content, id, now
func (_m *MockService) CreateRevision(ctx context.Context, userID uuid.UUID, sourceID uuid.UUID, title string, content string, id uuid.UUID, now time.Time) (*models.ImproveRequest, error) {
	ret := _m.Called(ctx, userID, sourceID, title, content, id, now)

	var r0 *models.ImproveRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, uuid.UUID, time.Time) (*models.ImproveRequest, error)); ok {
		return rf(ctx, userID, sourceID, title, content, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, uuid.UUID, time.Time) *models.ImproveRequest); ok {
		r0 = rf(ctx, userID, sourceID, title, content, id, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImproveRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, sourceID, title, content, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRevision'
type MockService_CreateRevision_Call struct {
	*mock.Call
}

// CreateRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sourceID uuid.UUID
//   - title string
//   - content string
//   - id uuid.UUID
//   - now time.Time
func (_e *MockService_Expecter) CreateRevision(ctx interface{}, userID interface{}, sourceID interface{}, title interface{}, content interface{}, id interface{}, now interface{}) *MockService_CreateRevision_Call {
	return &MockService_CreateRevision_Call{Call: _e.mock.On("CreateRevision", ctx, userID, sourceID, title, content, id, now)}
}

func (_c *MockService_CreateRevision_Call) Run(run func(ctx context.Context, userID uuid.UUID, sourceID uuid.UUID, title string, content string, id uuid.UUID, now time.Time)) *MockService_CreateRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(uuid.UUID), args[6].(time.Time))
	})
	return _c
}

func (_c *MockService_CreateRevision_Call) Return(_a0 *models.ImproveRequest, _a1 error) *MockService_CreateRevision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateRevision_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, uuid.UUID, time.Time) (*models.ImproveRequest, error)) *MockService_CreateRevision_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, requestID
func (_m *MockService) Delete(ctx context.Context, requestID uuid.UUID) error {
	ret := _m.Called(ctx, requestID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockService_Expecter) Delete(ctx interface{}, requestID interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, requestID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreviews provides a mock function with given fields: ctx, ids
func (_m *MockService) GetPreviews(ctx context.Context, ids []uuid.UUID) ([]*models.ImproveRequestPreview, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*models.ImproveRequestPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*models.ImproveRequestPreview, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*models.ImproveRequestPreview); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ImproveRequestPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreviews'
type MockService_GetPreviews_Call struct {
	*mock.Call
}

// GetPreviews is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockService_Expecter) GetPreviews(ctx interface{}, ids interface{}) *MockService_GetPreviews_Call {
	return &MockService_GetPreviews_Call{Call: _e.mock.On("GetPreviews", ctx, ids)}
}

func (_c *MockService_GetPreviews_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockService_GetPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetPreviews_Call) Return(_a0 []*models.ImproveRequestPreview, _a1 error) *MockService_GetPreviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetPreviews_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*models.ImproveRequestPreview, error)) *MockService_GetPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// IsCreator provides a mock function with given fields: ctx, userID, postID, strict
func (_m *MockService) IsCreator(ctx context.Context, userID uuid.UUID, postID uuid.UUID, strict bool) (bool, error) {
	ret := _m.Called(ctx, userID, postID, strict)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) (bool, error)); ok {
		return rf(ctx, userID, postID, strict)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) bool); ok {
		r0 = rf(ctx, userID, postID, strict)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, userID, postID, strict)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_IsCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCreator'
type MockService_IsCreator_Call struct {
	*mock.Call
}

// IsCreator is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - postID uuid.UUID
//   - strict bool
func (_e *MockService_Expecter) IsCreator(ctx interface{}, userID interface{}, postID interface{}, strict interface{}) *MockService_IsCreator_Call {
	return &MockService_IsCreator_Call{Call: _e.mock.On("IsCreator", ctx, userID, postID, strict)}
}

func (_c *MockService_IsCreator_Call) Run(run func(ctx context.Context, userID uuid.UUID, postID uuid.UUID, strict bool)) *MockService_IsCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockService_IsCreator_Call) Return(_a0 bool, _a1 error) *MockService_IsCreator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_IsCreator_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) (bool, error)) *MockService_IsCreator_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id
func (_m *MockService) Read(ctx context.Context, id uuid.UUID) (*models.ImproveRequest, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.ImproveRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.ImproveRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.ImproveRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImproveRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) Read(ctx interface{}, id interface{}) *MockService_Read_Call {
	return &MockService_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockService_Read_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_Read_Call) Return(_a0 *models.ImproveRequest, _a1 error) *MockService_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Read_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.ImproveRequest, error)) *MockService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRevisions provides a mock function with given fields: ctx, id
func (_m *MockService) ReadRevisions(ctx context.Context, id uuid.UUID) ([]*models.ImproveRequest, error) {
	ret := _m.Called(ctx, id)

	var r0 []*models.ImproveRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.ImproveRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.ImproveRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ImproveRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ReadRevisions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRevisions'
type MockService_ReadRevisions_Call struct {
	*mock.Call
}

// ReadRevisions is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) ReadRevisions(ctx interface{}, id interface{}) *MockService_ReadRevisions_Call {
	return &MockService_ReadRevisions_Call{Call: _e.mock.On("ReadRevisions", ctx, id)}
}

func (_c *MockService_ReadRevisions_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_ReadRevisions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_ReadRevisions_Call) Return(_a0 []*models.ImproveRequest, _a1 error) *MockService_ReadRevisions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ReadRevisions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*models.ImproveRequest, error)) *MockService_ReadRevisions_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, limit, offset
func (_m *MockService) Search(ctx context.Context, query models.ImproveRequestSearch, limit int, offset int) ([]*models.ImproveRequestPreview, int64, error) {
	ret := _m.Called(ctx, query, limit, offset)

	var r0 []*models.ImproveRequestPreview
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ImproveRequestSearch, int, int) ([]*models.ImproveRequestPreview, int64, error)); ok {
		return rf(ctx, query, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ImproveRequestSearch, int, int) []*models.ImproveRequestPreview); ok {
		r0 = rf(ctx, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ImproveRequestPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ImproveRequestSearch, int, int) int64); ok {
		r1 = rf(ctx, query, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.ImproveRequestSearch, int, int) error); ok {
		r2 = rf(ctx, query, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query ImproveRequestSearch
//   - limit int
//   - offset int
func (_e *MockService_Expecter) Search(ctx interface{}, query interface{}, limit interface{}, offset interface{}) *MockService_Search_Call {
	return &MockService_Search_Call{Call: _e.mock.On("Search", ctx, query, limit, offset)}
}

func (_c *MockService_Search_Call) Run(run func(ctx context.Context, query models.ImproveRequestSearch, limit int, offset int)) *MockService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ImproveRequestSearch), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockService_Search_Call) Return(_a0 []*models.ImproveRequestPreview, _a1 int64, _a2 error) *MockService_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_Search_Call) RunAndReturn(run func(context.Context, models.ImproveRequestSearch, int, int) ([]*models.ImproveRequestPreview, int64, error)) *MockService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// StorageToModel provides a mock function with given fields: source
func (_m *MockService) StorageToModel(source *improve_request_storage.Model) *models.ImproveRequest {
	ret := _m.Called(source)

	var r0 *models.ImproveRequest
	if rf, ok := ret.Get(0).(func(*improve_request_storage.Model) *models.ImproveRequest); ok {
		r0 = rf(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImproveRequest)
		}
	}

	return r0
}

// MockService_StorageToModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageToModel'
type MockService_StorageToModel_Call struct {
	*mock.Call
}

// StorageToModel is a helper method to define mock.On call
//   - source *improve_request_storage.Model
func (_e *MockService_Expecter) StorageToModel(source interface{}) *MockService_StorageToModel_Call {
	return &MockService_StorageToModel_Call{Call: _e.mock.On("StorageToModel", source)}
}

func (_c *MockService_StorageToModel_Call) Run(run func(source *improve_request_storage.Model)) *MockService_StorageToModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*improve_request_storage.Model))
	})
	return _c
}

func (_c *MockService_StorageToModel_Call) Return(_a0 *models.ImproveRequest) *MockService_StorageToModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_StorageToModel_Call) RunAndReturn(run func(*improve_request_storage.Model) *models.ImproveRequest) *MockService_StorageToModel_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t mockConstructorTestingTNewMockService) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
