// Code generated by mockery v2.16.0. DO NOT EDIT.

package profile_service

import (
	context "context"
	"github.com/a-novel/agora-backend/domains/user/storage/profile"
	"github.com/a-novel/agora-backend/models"

	mock "github.com/stretchr/testify/mock"
	time "time"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// PrepareRegistration provides a mock function with given fields: ctx, data
func (_m *MockService) PrepareRegistration(ctx context.Context, data *models.UserProfileUpdateForm) (*models.UserProfileRegistrationForm, error) {
	ret := _m.Called(ctx, data)

	var r0 *models.UserProfileRegistrationForm
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserProfileUpdateForm) *models.UserProfileRegistrationForm); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfileRegistrationForm)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.UserProfileUpdateForm) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_PrepareRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareRegistration'
type MockService_PrepareRegistration_Call struct {
	*mock.Call
}

// PrepareRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - data *UserProfileUpdateForm
func (_e *MockService_Expecter) PrepareRegistration(ctx interface{}, data interface{}) *MockService_PrepareRegistration_Call {
	return &MockService_PrepareRegistration_Call{Call: _e.mock.On("PrepareRegistration", ctx, data)}
}

func (_c *MockService_PrepareRegistration_Call) Run(run func(ctx context.Context, data *models.UserProfileUpdateForm)) *MockService_PrepareRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserProfileUpdateForm))
	})
	return _c
}

func (_c *MockService_PrepareRegistration_Call) Return(_a0 *models.UserProfileRegistrationForm, _a1 error) *MockService_PrepareRegistration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Read provides a mock function with given fields: ctx, id
func (_m *MockService) Read(ctx context.Context, id uuid.UUID) (*models.UserProfile, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.UserProfile
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.UserProfile); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) Read(ctx interface{}, id interface{}) *MockService_Read_Call {
	return &MockService_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockService_Read_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_Read_Call) Return(_a0 *models.UserProfile, _a1 error) *MockService_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ReadSlug provides a mock function with given fields: ctx, slug
func (_m *MockService) ReadSlug(ctx context.Context, slug string) (*models.UserProfile, error) {
	ret := _m.Called(ctx, slug)

	var r0 *models.UserProfile
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.UserProfile); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ReadSlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadSlug'
type MockService_ReadSlug_Call struct {
	*mock.Call
}

// ReadSlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockService_Expecter) ReadSlug(ctx interface{}, slug interface{}) *MockService_ReadSlug_Call {
	return &MockService_ReadSlug_Call{Call: _e.mock.On("ReadSlug", ctx, slug)}
}

func (_c *MockService_ReadSlug_Call) Run(run func(ctx context.Context, slug string)) *MockService_ReadSlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ReadSlug_Call) Return(_a0 *models.UserProfile, _a1 error) *MockService_ReadSlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SlugExists provides a mock function with given fields: ctx, slug
func (_m *MockService) SlugExists(ctx context.Context, slug string) (bool, error) {
	ret := _m.Called(ctx, slug)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SlugExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlugExists'
type MockService_SlugExists_Call struct {
	*mock.Call
}

// SlugExists is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockService_Expecter) SlugExists(ctx interface{}, slug interface{}) *MockService_SlugExists_Call {
	return &MockService_SlugExists_Call{Call: _e.mock.On("SlugExists", ctx, slug)}
}

func (_c *MockService_SlugExists_Call) Run(run func(ctx context.Context, slug string)) *MockService_SlugExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_SlugExists_Call) Return(_a0 bool, _a1 error) *MockService_SlugExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// StorageToModel provides a mock function with given fields: source
func (_m *MockService) StorageToModel(source *profile_storage.Model) *models.UserProfile {
	ret := _m.Called(source)

	var r0 *models.UserProfile
	if rf, ok := ret.Get(0).(func(*profile_storage.Model) *models.UserProfile); ok {
		r0 = rf(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	return r0
}

// MockService_StorageToModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageToModel'
type MockService_StorageToModel_Call struct {
	*mock.Call
}

// StorageToModel is a helper method to define mock.On call
//   - source *profile_storage.Model
func (_e *MockService_Expecter) StorageToModel(source interface{}) *MockService_StorageToModel_Call {
	return &MockService_StorageToModel_Call{Call: _e.mock.On("StorageToModel", source)}
}

func (_c *MockService_StorageToModel_Call) Run(run func(source *profile_storage.Model)) *MockService_StorageToModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*profile_storage.Model))
	})
	return _c
}

func (_c *MockService_StorageToModel_Call) Return(_a0 *models.UserProfile) *MockService_StorageToModel_Call {
	_c.Call.Return(_a0)
	return _c
}

// Update provides a mock function with given fields: ctx, data, id, now
func (_m *MockService) Update(ctx context.Context, data *models.UserProfileUpdateForm, id uuid.UUID, now time.Time) (*models.UserProfile, error) {
	ret := _m.Called(ctx, data, id, now)

	var r0 *models.UserProfile
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserProfileUpdateForm, uuid.UUID, time.Time) *models.UserProfile); ok {
		r0 = rf(ctx, data, id, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.UserProfileUpdateForm, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, data, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - data *UserProfileUpdateForm
//   - id uuid.UUID
//   - now time.Time
func (_e *MockService_Expecter) Update(ctx interface{}, data interface{}, id interface{}, now interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, data, id, now)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, data *models.UserProfileUpdateForm, id uuid.UUID, now time.Time)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserProfileUpdateForm), args[2].(uuid.UUID), args[3].(time.Time))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *models.UserProfile, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewMockService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t mockConstructorTestingTNewMockService) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
